#!/usr/bin/env python3
"""Regenerate runs/INDEX.md — auto-index of all experiment run directories.

Lists every directory under ``runs/`` with:
  - Run name (directory name)
  - Timestamp (from env.json ``started_at`` if available)
  - Model (from env.json ``model_path`` if available)
  - Status (REPORT.md exists → complete, else pending)
  - REPORT link

Usage::

    python scripts/regen_runs_index.py
    # or from repo root:
    make runs-index

Makefile target (add to Makefile)::

    runs-index:
        python scripts/regen_runs_index.py

The script is safe to run repeatedly; it overwrites ``runs/INDEX.md`` in place.
It also performs the authenticity check: warns if any run dir is missing
``cells.jsonl`` or ``env.json``.

Exit code 0 even if some runs are incomplete (warnings only for missing files).
Exit code 1 if ``--strict`` is passed and any run is missing required files.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Optional

RUNS_DIR = Path(__file__).resolve().parents[1] / "runs"
INDEX_PATH = RUNS_DIR / "INDEX.md"

REQUIRED_FILES = {"cells.jsonl", "env.json"}


def _read_env(run_dir: Path) -> dict:
    env_path = run_dir / "env.json"
    if not env_path.exists():
        return {}
    try:
        return json.loads(env_path.read_text())
    except json.JSONDecodeError:
        return {}


def _run_status(run_dir: Path) -> str:
    if (run_dir / "REPORT.md").exists():
        # Check if it's a placeholder ("pending")
        content = (run_dir / "REPORT.md").read_text()
        if "⏳ Pending" in content or "Pending execution" in content:
            return "⏳ pending"
        return "✅ complete"
    return "🔄 in-progress"


def _missing_files(run_dir: Path) -> list[str]:
    return [f for f in REQUIRED_FILES if not (run_dir / f).exists()]


def iter_runs(runs_dir: Path):
    for d in sorted(runs_dir.iterdir()):
        if d.is_dir() and not d.name.startswith("."):
            yield d


def build_index(strict: bool = False) -> tuple[str, list[str]]:
    """Build the INDEX.md content.

    Returns
    -------
    (content: str, warnings: list[str])
    """
    rows = []
    warnings = []

    for run_dir in iter_runs(RUNS_DIR):
        env = _read_env(run_dir)
        started = env.get("started_at", env.get("commit", "")[:8] if env.get("commit") else "—")
        model_path: str = env.get("model_path", "")
        model_short = Path(model_path).name if model_path else "—"
        status = _run_status(run_dir)
        has_report = (run_dir / "REPORT.md").exists()
        report_link = f"[REPORT]({run_dir.name}/REPORT.md)" if has_report else "—"

        missing = _missing_files(run_dir)
        auth_flag = ""
        if missing:
            auth_flag = f" ⚠️ missing: {', '.join(missing)}"
            warnings.append(f"{run_dir.name}: missing {missing}")

        rows.append({
            "name": run_dir.name,
            "started": started[:16] if len(started) > 16 else started,
            "model": model_short,
            "status": status + auth_flag,
            "report": report_link,
        })

    # Header
    lines = [
        "# Runs Index",
        "",
        "Auto-generated by `scripts/regen_runs_index.py`.  Re-run to refresh.",
        "",
        f"**Total runs**: {len(rows)}",
        "",
        "| Run | Started | Model | Status | Report |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['name']}` | {r['started']} | `{r['model']}` | {r['status']} | {r['report']} |"
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Authenticity Requirements")
    lines.append("")
    lines.append(
        "Every run directory **must** contain `cells.jsonl` and `env.json` "
        "before being considered a valid evidence artifact. "
        "Runs flagged with ⚠️ above are missing required files."
    )
    lines.append("")

    if warnings:
        lines.append("## Warnings")
        lines.append("")
        for w in warnings:
            lines.append(f"- ⚠️ `{w}`")
        lines.append("")

    content = "\n".join(lines)
    return content, warnings


def main():
    ap = argparse.ArgumentParser(description="Regenerate runs/INDEX.md")
    ap.add_argument(
        "--strict",
        action="store_true",
        help="Exit 1 if any run is missing cells.jsonl or env.json",
    )
    ap.add_argument(
        "--check-only",
        action="store_true",
        help="Print warnings but do not write INDEX.md; exit 1 if any missing files",
    )
    args = ap.parse_args()

    content, warnings = build_index(strict=args.strict)

    if not args.check_only:
        INDEX_PATH.write_text(content)
        print(f"Wrote {INDEX_PATH}")

    if warnings:
        print(f"\n{len(warnings)} authenticity warning(s):")
        for w in warnings:
            print(f"  ⚠️  {w}")
        if args.strict or args.check_only:
            sys.exit(1)
    else:
        print("All run directories have required files ✅")


if __name__ == "__main__":
    main()
