"""Phase L4-rev: bank_topk sweep for v3.1 K-projector.

For a fixed v3.1 K-projector and split, sweep ``bank_topk ∈ {0,1,2,4,8,16}``
to test whether softmax dilution is the dominant bottleneck. ``0`` = full
N-way softmax (legacy v3 behavior). Recall@1 reported per topk.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import torch

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from deltamemory.memory.attn_native_bank import AttnNativePatcher  # noqa: E402
from deltamemory.memory.k_projector import KProjectorBank  # noqa: E402
from scripts.run_stage14_test_eval import _load_test, _recall_with_bank  # noqa: E402


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="google/gemma-4-E2B")
    ap.add_argument("--device", default="mps")
    ap.add_argument("--projector",
                    default="reports/cleanroom/stage15_kproj_v31/k_projector_gemma4.pt")
    ap.add_argument("--split", default="eval/splits_v31/dev_v31.jsonl")
    ap.add_argument("--seeds", default="0")
    ap.add_argument("--topk-list", default="0,1,2,4,8,16")
    ap.add_argument("--tau-list", default="1.0")
    ap.add_argument("--out", default="reports/cleanroom/stage15_topk_sweep")
    ap.add_argument("--cosine", action="store_true", help="enable bank_cosine")
    ap.add_argument("--separate", action="store_true",
                    help="enable bank_separate_softmax")
    ap.add_argument("--beta", type=float, default=1.0,
                    help="bank_merge_beta when --separate")
    ap.add_argument("--dtype", default="bfloat16",
                    choices=["bfloat16", "float16", "float32"],
                    help="model dtype (use float32 to bypass GB10 bf16 numerical issues)")
    args = ap.parse_args()

    seeds = [int(s) for s in args.seeds.split(",") if s.strip()]
    topks = [int(t) for t in args.topk_list.split(",") if t.strip()]
    taus = [float(t) for t in args.tau_list.split(",") if t.strip()]

    facts = _load_test(Path(args.split))
    print(f"[topk-sweep] N={len(facts)} facts, split={args.split}", flush=True)

    dtype_map = {"bfloat16": torch.bfloat16, "float16": torch.float16, "float32": torch.float32}
    torch_dtype = dtype_map[args.dtype]

    from transformers import AutoModelForCausalLM, AutoTokenizer
    print(f"[topk-sweep] loading {args.model} dtype={args.dtype}…", flush=True)
    t0 = time.time()
    tok = AutoTokenizer.from_pretrained(args.model)
    model = AutoModelForCausalLM.from_pretrained(
        args.model, torch_dtype=torch_dtype, attn_implementation="eager"
    )
    model.to(args.device).eval()
    print(f"[topk-sweep] model ready in {time.time()-t0:.1f}s", flush=True)

    patcher = AttnNativePatcher(model)
    proj = KProjectorBank.load(args.projector)

    out_dir = REPO_ROOT / args.out
    out_dir.mkdir(parents=True, exist_ok=True)

    rows: list[dict] = []
    for tau in taus:
        for topk in topks:
            for s in seeds:
                pf = _recall_with_bank(
                    patcher, tok, facts,
                    policy="period",
                    k_projector=proj,
                    tau=tau,
                    seed=s,
                    bank_topk=topk,
                    bank_cosine=args.cosine,
                    bank_separate_softmax=args.separate,
                    bank_merge_beta=args.beta,
                )
                m = sum(pf) / max(len(pf), 1)
                row = {"tau": tau, "bank_topk": topk, "seed": s,
                       "cosine": args.cosine, "separate": args.separate,
                       "beta": args.beta,
                       "recall_at_1_mean": m, "per_fact": pf}
                rows.append(row)
                tag = f"cos={int(args.cosine)} sep={int(args.separate)} b={args.beta}"
                print(f"[topk-sweep] tau={tau} topk={topk:>2} {tag} seed={s} "
                      f"recall@1={m:.4f}",
                      flush=True)

    (out_dir / "summary.json").write_text(json.dumps(rows, indent=2))

    md = ["# Phase L4-rev: bank_topk sweep (v3.1 K-projector)\n",
          f"**Split**: `{args.split}` (N={len(facts)})",
          f"**Projector**: `{args.projector}`",
          f"**Device**: {args.device}, bf16, model={args.model}\n",
          "## Recall@1 by (tau, bank_topk)\n",
          "| tau | bank_topk | seed | recall@1 |",
          "|---:|---:|---:|---:|"]
    for r in rows:
        md.append(f"| {r['tau']} | {r['bank_topk']} | {r['seed']} | "
                  f"{r['recall_at_1_mean']:.4f} |")
    md.append("\nGenerated by `scripts/run_v31_topk_sweep.py`.\n")
    (out_dir / "REPORT.md").write_text("\n".join(md))
    print(f"[topk-sweep] wrote {out_dir/'REPORT.md'}", flush=True)


if __name__ == "__main__":
    main()
