"""Re-evaluate v3 on dev with the trained K-projector attached.

This is the smoking-gun test: if the trained Stage 14A InfoNCE projector
actually fixes the K-space mismatch, v3_multi_kproj should beat both the
no-memory baseline (B0) and the broken v2 baseline (which collapsed to
0.000 at N=33).
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

import torch

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from scripts.run_stage14_dev_sweep import (  # noqa: E402
    _eval_condition,
    _load_dev,
)
from deltamemory.memory.attn_native_bank import AttnNativePatcher  # noqa: E402
from deltamemory.memory.k_projector import KProjectorBank  # noqa: E402


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default="google/gemma-4-E2B")
    ap.add_argument("--device", default="mps")
    ap.add_argument(
        "--projector",
        default="reports/cleanroom/stage14_kproj/k_projector.pt",
    )
    ap.add_argument("--seeds", default="0,1,2")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--out", default="reports/cleanroom/stage14_dev_kproj")
    args = ap.parse_args()

    seeds = [int(s) for s in args.seeds.split(",") if s.strip()]
    facts = _load_dev()
    if args.limit > 0:
        facts = facts[: args.limit]

    from transformers import AutoModelForCausalLM, AutoTokenizer

    print(f"[stage14-dev-kproj] loading {args.model}…", flush=True)
    t0 = time.time()
    tok = AutoTokenizer.from_pretrained(args.model)
    model = AutoModelForCausalLM.from_pretrained(args.model, torch_dtype=torch.bfloat16)
    model.to(args.device).eval()
    print(f"[stage14-dev-kproj] model ready in {time.time() - t0:.1f}s", flush=True)

    patcher = AttnNativePatcher(model)
    proj = KProjectorBank.load(args.projector)

    # Wrap _eval_condition to attach projector after fresh_bank.
    def eval_with_proj(name, policy, tau):
        seeds_rows = []
        for seed in seeds:
            from deltamemory.memory.attn_native_bank import (
                fresh_bank,
                write_fact,
                forward_with_bank,
            )
            import random

            rng = random.Random(seed)
            order = list(range(len(facts)))
            rng.shuffle(order)
            bank = fresh_bank(model)
            bank.bank_temperature = tau
            bank.k_projector = proj  # <- the actual difference

            if policy is not None:
                for i in order:
                    f = facts[i]
                    write_fact(
                        patcher=patcher,
                        bank=bank,
                        tokenizer=tok,
                        write_prompt=f.write_prompt,
                        fact_id=f.fact_id,
                        address=f.address,
                        policy=policy,
                    )
            per_fact = []
            for f in facts:
                target_ids = tok(" " + f.value, add_special_tokens=False)["input_ids"]
                tid = int(target_ids[0]) if target_ids else int(
                    tok(f.value, add_special_tokens=False)["input_ids"][0]
                )
                hits = 0
                n = 0
                for p in f.paraphrases:
                    logits = forward_with_bank(patcher, bank, tok, p, alpha=1.0 if policy else 0.0)
                    hits += int(int(logits.argmax().item()) == tid)
                    n += 1
                per_fact.append(hits / max(n, 1))
            r = sum(per_fact) / max(len(per_fact), 1)
            seeds_rows.append({"seed": seed, "recall_at_1_mean": r, "per_fact": per_fact})
            print(f"[stage14-dev-kproj] {name} seed={seed} recall@1={r:.4f}", flush=True)
        return seeds_rows

    conditions = [
        ("B0_no_memory_kproj_attached", None, 1.0),
        ("v3_period_kproj", "period", 1.0),
        ("v3_address_kproj", "address", 1.0),
        ("v3_multi_kproj", "multi", 1.0),
        ("v3_multi_kproj_tau05", "multi", 0.5),
    ]

    out_dir = REPO_ROOT / args.out
    out_dir.mkdir(parents=True, exist_ok=True)
    all_rows = {}
    for name, policy, tau in conditions:
        all_rows[name] = eval_with_proj(name, policy, tau)
    (out_dir / "summary.json").write_text(json.dumps(all_rows, indent=2))

    md = ["# Stage 14 dev sweep — K-projector ATTACHED — Gemma-4-E2B / dev (33 facts)\n"]
    md.append("| condition | mean | per-seed |")
    md.append("|---|---:|---|")
    for name, rows in all_rows.items():
        m = sum(r["recall_at_1_mean"] for r in rows) / max(len(rows), 1)
        per = ", ".join(f"{r['recall_at_1_mean']:.3f}" for r in rows)
        md.append(f"| {name} | {m:.3f} | {per} |")
    md.append("\nGenerated by `scripts/run_stage14_dev_with_kproj.py`.\n")
    (out_dir / "REPORT.md").write_text("\n".join(md))
    print(f"[stage14-dev-kproj] wrote {out_dir/'REPORT.md'}", flush=True)


if __name__ == "__main__":
    main()
